# This is a hello world HOT template just defining a single compute instance
heat_template_version: 2013-05-23

description: >
  SR-IOV HOT template that just defines a single compute instance.
  Contains just base features.
  heat stack-create PciPort -f /home/openstack/pci.yaml  

parameters:
  Keyname:
    type: string
    description: Name of an existing key pair to use for the instance
    default: heat_key
  InstanceType:
    type: string
    description: Instance type for the instance to be created
    default: m1.large
  ImageId:
    type: string
    description: ID of the image to use for the instance
    default: ubuntu_precise
  my_net:
    type: string
    description: the net
    default: private


resources:
#  my_port:
#    type: OS::Neutron::SriovPort
#    #type: OS::Neutron::PciPort
#    properties:
#      network: { get_param: my_net }
#      #vnic_type: normal
#      #value_specs: { "binding:vnic_type": normal}

  my_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: my_net }
      #vnic_type: direct
      vnic_type: normal
      replacement_policy: AUTO

#  sriov_instance:
#    type: OS::Nova::Server
#    properties:
#      name: sr-iov
#      key_name: { get_param: Keyname }
#      image: { get_param: ImageId }
#      flavor: { get_param: InstanceType }
#      networks:
#        - port: { get_resource: sriov_port }

outputs:
  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [my_port, status] }
    #value: { get_attr: [sriov_instance, networks] }

